const strings = [
    [ "transfer", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "Transfer", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "PayNow", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "paynow", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "pay", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "fast", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "FAST", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "Fast", "Sending Money Via PayNow/Bank Transfer will be disabled till further notice.\nHowever, you can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "Hi!", "How can I help you?" ],
    [ "hi", "How can I help you?" ],
    [ "atm", "You can't use your GET card at any local ATM to do,\n- Bank Transfer / FAST\n- Cash Withdrawal\n- Cash Deposit\n- Check Balance\n- Anything else you can imagine off\n\nCurrently, Singapore government / MAS regulations don't allow e-money providers like Get to have their users withdraw money from their Get accounts from the ATMs at the moment, though we're working on a solution, and will announce it once launched!\n\nMeantime, you'll need to send it out  locally (PayNow/FAST) to a friend / another account via Get local transfer, or spend it, if you really need to.\n\nHowever, you can use the GET card at any overseas ATMs that support Visa." ],
    [ "Atm", "You can't use your GET card at any local ATM to do,\n- Bank Transfer / FAST\n- Cash Withdrawal\n- Cash Deposit\n- Check Balance\n- Anything else you can imagine off\n\nCurrently, Singapore government / MAS regulations don't allow e-money providers like Get to have their users withdraw money from their Get accounts from the ATMs at the moment, though we're working on a solution, and will announce it once launched!\n\nMeantime, you'll need to send it out  locally (PayNow/FAST) to a friend / another account via Get local transfer, or spend it, if you really need to.\n\nHowever, you can use the GET card at any overseas ATMs that support Visa." ],
    [ "ATM", "You can't use your GET card at any local ATM to do,\n- Bank Transfer / FAST\n- Cash Withdrawal\n- Cash Deposit\n- Check Balance\n- Anything else you can imagine off\n\nCurrently, Singapore government / MAS regulations don't allow e-money providers like Get to have their users withdraw money from their Get accounts from the ATMs at the moment, though we're working on a solution, and will announce it once launched!\n\nMeantime, you'll need to send it out  locally (PayNow/FAST) to a friend / another account via Get local transfer, or spend it, if you really need to.\n\nHowever, you can use the GET card at any overseas ATMs that support Visa." ],
    [ "otp", "Please call us at +65 3105 1380 for OTP support." ],
    [ "deposit", "You can't withdraw or cash deposit at any Local ATM unless overseas ATM's." ],
    [ "withdraw", "You can't withdraw or cash deposit at any Local ATM unless overseas ATM's." ],
    [ "Deposit", "You can't withdraw or cash deposit at any Local ATM unless overseas ATM's." ],
    [ "Withdraw", "You can't withdraw or cash deposit at any Local ATM unless overseas ATM's." ],
    [ "error", "Please send a screen-recording/screenshot of the error." ],
    [ "Topup", "You can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "top-up", "You can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "topup", "You can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "Top-Up", "You can still Receive + Add Money to your Get account via PayNow QR¹ or Debit/Credit card!" ],
    [ "topped", "1) Please refresh/restart the app.\n2) Check if you have received any topup sms/email from us at that timing.\n3) GET app balance may not be updated but you may still be able to spend it.\n4) Contact us via the in-app chat for more information." ],
    [ "toped", "1) Please refresh/restart the app.\n2) Check if you have received any topup sms/email from us at that timing.\n3) GET app balance may not be updated but you may still be able to spend it.\n4) Contact us via the in-app chat for more information." ],
]
